"""
Emilee Urbanek and Nick Confrey
CMSC 22010: Digital Fabrication
Lab 3
Due: 4/25

---

The GCode file
This is supposed to generate GCode given perimeters......
I'm not even sure if it's going to be a class or not....
Handles layers and stuff and also setup and cleanup
"""

def generateSetup(gfile, params):
  """Generates the setup GCode preceeding all of the printing

  Keyword arguments:
  gfile -- A file already open for writing the gcode to
  """
  gfile.write("; Generated by Nick&Em's Slycer at 'I'm too lazy to import datetime'C\n")
  gfile.write("\n")

  gfile.write("; Perimeter Layers: {}\n".format(params.perimeterLayers))
  gfile.write("; Infill: {}%%\n".format(params.infill * 100))
  gfile.write("; Layer Height: {}mm\n".format(params.layerHeight))
  gfile.write("; Nozzle Size: {}mm\n".format(params.thickness))
  gfile.write("; Support {}\n".format("On" if params.support else "Off"))
  gfile.write("; Temperature {} degrees C\n".format(params.temperature))
  gfile.write("\n")

  gfile.write("; SETUP\n")
  lines = [
    "M107 ; fan off",
    "M104 S{d} ; set temperature".format(params.temperature),
    "G28 X0 Y0 Z0 ; home all axes",
    "G1 Z5 F5000 ; lift nozzle",
    "",
    "M109 S{d} ; wait for temperature to be reached".format(params.temperature),
    "G21 ; set units to millimeters",
    "G90 ; use absolute coordinates",
    "M82 ; use absolute distances for extrusion",
    "G1 Z{:1.3f} F2400 ; put printhead at good distance from bed".format(params.thickness),
    "G92 E0",
    "G29 ; idk but cura does this to touch the corners",
    # right here, we want to find an appropriate place to set the 0 for x and y
    # we want to move there (G1) and then set it as 0 (G92 X0 Y0 Z0)
    ""
  ]
  gfile.write("\n".join(lines))

def generateGCode(gfile, perimeters):
  pass # TODO